// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PyStudio.Model.Models;
using System;

namespace PyStudio.Model.Migrations
{
    [DbContext(typeof(PyStudioDBContext))]
    partial class PyStudioDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("PyStudio.Model.Models.Account.InfoUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserAddress")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("UserBirthday")
                        .HasColumnType("date");

                    b.Property<string>("UserBlog")
                        .HasMaxLength(200);

                    b.Property<DateTime>("UserCreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(50);

                    b.Property<string>("UserHeadPhoto")
                        .HasMaxLength(50);

                    b.Property<string>("UserIntroduce")
                        .HasMaxLength(200);

                    b.Property<string>("UserIps")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UserLoginTime")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserNickName")
                        .HasMaxLength(50);

                    b.Property<string>("UserPwd")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("UserSex")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("'2'");

                    b.Property<int>("UserStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("UserTel")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.ToTable("InfoUser");
                });

            modelBuilder.Entity("PyStudio.Model.Models.BaseInfo.InfoArea", b =>
                {
                    b.Property<int>("AreaId");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(50);

                    b.Property<string>("AreaCoord")
                        .HasMaxLength(50);

                    b.Property<int>("AreaLevel")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("AreaName")
                        .HasMaxLength(50);

                    b.Property<string>("AreaNote")
                        .HasMaxLength(150);

                    b.Property<string>("AreaPathId")
                        .HasMaxLength(100);

                    b.Property<string>("AreaPid")
                        .HasMaxLength(50);

                    b.Property<string>("AreaZipCode")
                        .HasMaxLength(50);

                    b.HasKey("AreaId");

                    b.ToTable("InfoArea");
                });

            modelBuilder.Entity("PyStudio.Model.Models.BaseInfo.InfoEi", b =>
                {
                    b.Property<string>("Eicol1")
                        .HasMaxLength(50);

                    b.Property<string>("Eicol2")
                        .HasMaxLength(50);

                    b.Property<string>("Eicol3")
                        .HasMaxLength(50);

                    b.Property<string>("Eicol4")
                        .HasMaxLength(50);

                    b.HasKey("Eicol1");

                    b.ToTable("InfoEi");
                });

            modelBuilder.Entity("PyStudio.Model.Models.SmallApp.InfoMessageBoard", b =>
                {
                    b.Property<int>("MessageBoardId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MessageBoardContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("MessageBoardCreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MessageBoardIp")
                        .HasMaxLength(50);

                    b.Property<string>("MessageBoardUser")
                        .HasMaxLength(100);

                    b.HasKey("MessageBoardId");

                    b.ToTable("InfoMessageBoard");
                });

            modelBuilder.Entity("PyStudio.Model.Models.Sys.SysLogger", b =>
                {
                    b.Property<int>("LoggerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("LoggerCreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("LoggerDescription")
                        .HasColumnType("text");

                    b.Property<string>("LoggerIps")
                        .HasMaxLength(50);

                    b.Property<int?>("LoggerOperation");

                    b.Property<int?>("LoggerUser");

                    b.HasKey("LoggerId");

                    b.HasIndex("LoggerUser");

                    b.ToTable("SysLogger");
                });

            modelBuilder.Entity("PyStudio.Model.Models.Sys.SysLogger", b =>
                {
                    b.HasOne("PyStudio.Model.Models.Account.InfoUser", "User")
                        .WithMany("SysLogger")
                        .HasForeignKey("LoggerUser")
                        .HasConstraintName("FK_SysLogger_InfoUser");
                });
#pragma warning restore 612, 618
        }
    }
}
